name: Basic test on Windows

on: [push]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust_toolchain: stable
    steps:
      - uses: actions/checkout@v4

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Compile UniV with algorithms and generate headers
        run: set RUST_BACKTRACE=full && cargo run --features dev -- --compile-algos --with-headers