name: Basic test on macOS

on: [push]

jobs:
  test:
    name: Test on macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]
        include:
          - os: macos-latest
            rust_toolchain: stable
          - os: macos-15-intel
            rust_toolchain: stable
    steps:
      - uses: actions/checkout@v4

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Compile UniV with algorithms and generate headers
        run: RUST_BACKTRACE=full cargo run --features dev -- --compile-algos --with-headers